# -*- mode: makefile; -*-

BOOST_LIBS =                                    \
    $(BOOST_SYSTEM_LIBS)                        \
    $(BOOST_THREAD_LIBS)                        \
    $(BOOST_TIMER_LIBS)

AM_CPPFLAGS = -I. -I$(top_srcdir)/include $(BOOST_CPPFLAGS)
AM_LDFLAGS = $(BOOST_LDFLAGS)

LIBS = $(BOOST_LIBS)
